### ISSUE TITLE
Issue About pseudo code

### ISSUE THREAD

**Issue by NingMa-AI** [vlpolyansky/voronoi-boundary-classifier#1]
Thanks for sharing your code!  I want to follow your work these day,but I do not understand the 12th line in  the pseudo code of paper.How do you sample a D dimension vector form D-1 dimension?
And in Lemma 2 ,paper shown <m,x-t> ,I do not understand how to calculate inner product of a D dimension vector (x-t) and D-1 dimension m.
thanks!

**Comment by vlpolyansky** [comment]
Hi, I'll just leave a copy of the answer from my email here.

In the 12th line of the algorithm, we indeed sample a point on a (D-1)-dimensional sphere. However, this sphere is embedded into D-dimensional space R^D. The dimensionality of a hypersphere is one less than the dimensionality of space containing it, and we look at a sampled point from R^D perspective.

Same goes for Lemma 2, m is in fact a D-dimensional vector with length 1.
